name: bucket
version: 1.0.0
main: top.cxkcxkckx.bucket.bucket
api-version: 1.16
depend: [  ]
softdepend: [ PlaceholderAPI ]
authors: [ cxkcxkckx ]
commands:
  example:
    description: 'The main command of ExmaplePlugin'
  getbucket:
    description: 获取锁分通
    usage: /<command>
    permission: bucket.get
permissions:
  bucket.get:
    description: 允许使用获取锁分桶命令
    default: op
